
=== Ssstrict

The Ssstrict extension indicates that executing unimplemented instructions or accessing unimplemented CSR in the standard or reserved encoding spaces raises an illegal instruction exception.

[quote, https://github.com/riscv/riscv-profiles/blob/main/src/rva23-profile.adoc[RVA23 profile Ssstrict definition]]
No non-conforming extensions are present. Attempts to execute unimplemented opcodes
or access unimplemented CSRs in the standard or reserved encoding spaces raises an illegal
instruction exception that results in a contained trap to the supervisor-mode trap handler.

Vector instructions introduce complex register constraints and are tested separately in <<SsstrictV>>.

==== SsstrictSm

RISC-V does not have a ratified equivalent of Ssstrict for machine mode, but this optional test suite checks the behavior of unimplemented instructions and CSRs from machine mode.  It runs the same tests as SsstrictS but from machine mode.

==== SsstrictS

Attempt to issue all flavors of 32-bit instructions in the standard and reserved spaces and all 16-bit compressed instructions.  Also attempt to access all CSRs in the standard and reserved spaces that should be inaccessible.  Expect illegal instruction trap for unimplemented instructions and CSRs, matching reference model.

According to the RVA23 profile spec, the illegal instruction should be cause a trap to the supervisor trap handler.  However, delegation is the business of the firmware, not the hardware.  These tests only check that a trap occurs and matches the reference model.

[[t-SsstrictS-coverpoints]]
.SsstrictS Coverpoints
https://docs.google.com/spreadsheets/d/1qJsCYdDPaSxNE1R56jsAUyoAiu4OhMlwwAvGysgx790/edit?gid=593261374#gid=593261374[Google Sheet Testplan]

include::norm/SsstrictS_norm_rules.adoc[]

==== SsstrictU

Same as SsstrictS, but runs from user mode and includes attempts to access supervisor CSRs that should be inaccessible from user mode.
